#!/bin/sh
set -e

#Enable SSH
sed -i 's/#PermitRootLogin .*/PermitRootLogin yes/' /etc/ssh/sshd_config
sed -i 's/#PermitEmptyPasswords .*/PermitEmptyPasswords yes/' /etc/ssh/sshd_config
echo 'root:root' | chpasswd
echo 'exec /usr/bin/vtysh' >> ~/.bashrc
/etc/init.d/ssh start



#Enable daemons
sed -i "s/bgpd=no/bgpd=yes/g" /etc/frr/daemons
sed -i "s/ospfd=no/ospfd=yes/g" /etc/frr/daemons
chown -R frr:frr /etc/frr
/etc/init.d/frr start



#Launch continous command
exec sleep 10000d
